### ISSUE TITLE
README usage example

### ISSUE THREAD

**Issue by heemayl** [Wozinga/bitxchange_python_api#1]
In the `README` usage example, there's a typo; the variable `clilent` in `order = client.create_order(**params)` should be `order = exchange.create_order(**params)` i.e. we need to replace `client` with `exchange` as we instantiated the `Spot` class as `exchange = Spot(key='<api_key ', secret='api_secret')`.

**Comment by 30ThreeDegrees** [comment]
Great feedback, correction has been made.

commit abba345da16952989326fb76cbafd1175d9db6f9
