### ISSUE TITLE
Version should be accessible as `bitxchange.__version__` (or `bitxchange.version`)

### ISSUE THREAD

**Issue by heemayl** [Wozinga/bitxchange_python_api#2]
If the user wants to check the version, currently they need to do:

```python
bitxchange.__version__.__version__
```

which is counter-intuitive IMO. We can import the `__version__` in the [`bitxchange/__init__.py`](https://github.com/Wozinga/bitxchange_python_api/blob/v.0.0.2/bitxchange/__init__.py) file:

```python
from .__version__ import __version__ 
``` 

to let the user easily check the version:

```python
bitxchange.__version__
```

(also the `bitxchange.__version__.__version__` would still be available).

**Comment by 30ThreeDegrees** [comment]
Fixed commit 820ddb2b5f270e34fa1e94605416b8fe698ca66a
