### ISSUE TITLE
Fragile string concatenation

### ISSUE THREAD

**Issue by heemayl** [Wozinga/bitxchange_python_api#4]
f-strings or `str.format` should be used for string concatenation. Using `+` would fail as there is no implicit `str` conversion is done so if one of the operands is non-`str` the concatenation would raise a `TypeError`.

For example, this https://github.com/Wozinga/bitxchange_python_api/blob/v.0.0.2/bitxchange/api.py#L46:

```python
url = self.base_url + url_path
```

could be written as:

```python
url = f"{self.base_url}{url_path}"
```

As an aside, when dealing with joining URLs, `urllib.parse.urljoin` might be a better option:

```python
from urllib.parse import urljoin

urljoin(self.base_url, url_path) 
```

---

Also, we don't need to use `printf` style formatting as they are arguably not readable enough and the type of the arguments not much important when we want to convert everything to a string:

For example, this https://github.com/Wozinga/bitxchange_python_api/blob/cc62dc0f7073f6e68ffc6d71fea33da35db44285/bitxchange/errors.py#L18:

could be written as:

```python
        return "{(', '.join(self.params)} is mandatory, but received empty."
```

If putting `str.join` inside f-strings seems a bit less readable, `str.format` can be used or even assigning the `join` output to a variable first and then we can use the variable name inside f-string:

```python
        return "{} is mandatory, but received empty.".format(", ".join(self.params))
```

**Comment by 30ThreeDegrees** [comment]
Great feedback, the changes have been implemented and will be added to the v0.0.2 release.

commit c8ec271fe74c44d5ccf5ed495cff98283b76e3ef
