### ISSUE TITLE
Comment should be a docstring

### ISSUE THREAD

**Issue by heemayl** [Wozinga/bitxchange_python_api#5]
This comment https://github.com/Wozinga/bitxchange_python_api/blob/cc62dc0f7073f6e68ffc6d71fea33da35db44285/bitxchange/lib/shared_utils.py#L8 should be a docstring so that it's available in the `help` call.

**returns a clean dict** bit there is very important as `dict`s are mutable.

**Comment by 30ThreeDegrees** [comment]
Great feedback, changes have been implemented and will be released in v0.0.2

commit c68034d9c29dc33d3608614292d5ff9091952c01
